version: 0.2

env:
  variables:
    RUNNER_ALLOW_RUNASROOT: "1"
    RUNNER_WORKDIR: "/root/actions-runner"
    RUNNER_GROUP: "ATTRunner"
    GITHUB_ORG: "tyagirajATnT"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd /root
      - mkdir -p actions-runner && cd actions-runner
      - curl -o actions-runner-linux-x64-2.311.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-x64-2.311.0.tar.gz
      - tar xzf ./actions-runner-linux-x64-2.311.0.tar.gz
      - rm actions-runner-linux-x64-2.311.0.tar.gz
      
  pre_build:
    commands:
      - TOKEN=$(curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/orgs/${GITHUB_ORG}/actions/runners/registration-token | jq -r .token)
      - ./config.sh --url https://github.com/${GITHUB_ORG} --token ${TOKEN} --name "aws-codebuild-runner" --runnergroup ${RUNNER_GROUP} --labels aws-codebuild,linux,x64 --unattended --ephemeral
      
  build:
    commands:
      - ./run.sh

  post_build:
    commands:
      - echo "Runner job completed"
