version: 0.2

env:
  variables:
    RUNNER_ALLOW_RUNASROOT: "1"
    RUNNER_WORKDIR: "/root/actions-runner"
    RUNNER_GROUP: "ATTRunner"
    GITHUB_ORG: "tyagirajATnT"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd /root
      - mkdir -p actions-runner && cd actions-runner
      - curl -o actions-runner-linux-x64-2.311.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-x64-2.311.0.tar.gz
      - tar xzf ./actions-runner-linux-x64-2.311.0.tar.gz
      - rm actions-runner-linux-x64-2.311.0.tar.gz
      
  pre_build:
    commands:
      - cd /root/actions-runner
      - |
        TOKEN=$(curl -X POST \
          -H "Authorization: Bearer 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" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/orgs/tyagirajATnT/actions/runners/registration-token" | 
          jq -r .token)
      - echo "Token acquisition status:" $?
      - |
        if [ -z "$TOKEN" ]; then
          echo "Failed to acquire token. Response:"
          curl -H "Authorization: Bearer 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" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/tyagirajATnT"
          exit 1
        fi
      - echo "Token acquired successfully"
      - ./config.sh --url "https://github.com/tyagirajATnT" --token ${TOKEN} --name "aws-codebuild-runner" --runnergroup "ATTRunner" --labels aws-codebuild,linux,x64 --unattended --ephemeral
      - echo "Runner configuration exit code:" $?    
  build:
    commands:
      - cd /root/actions-runner
      - ./run.sh &
      - sleep 30    # Give the runner time to connect
      - |
        while true; do
          if ! pgrep -f "./run.sh" > /dev/null; then
            echo "Runner process has stopped"
            exit 1
          fi
          sleep 60
        done

  post_build:
    commands:
      - echo "Runner job completed"
      
