name: CodeBuild with Runner Group

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-codebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIA32WXPXTCGGJ5MCFM
        aws-secret-access-key: GG8vXFBO2LwRTS9KLKpixae6px1WTpPCCJW6BfC0
        aws-session-token: IQoJb3JpZ2luX2VjEM///////////wEaCXVzLWVhc3QtMSJIMEYCIQDdBpsrYGcV7/bY1PCgSRVKyI1D9c8UZlFmQH+VQJrAlQIhAPpZseaSf9q1XxDeADqgKe6Rij0PS6vUtXjYMpd16rghKqgCCIj//////////wEQAhoMODEzMjc0NDc5ODEyIgwtUA21A25sGYaY+PUq/AGVRPyzo0FIsO8dCJQh4s/ov/ztqv0UGBjwAsixV1xewRlKSrUmn6FRi4pzO3GZw9uAZGb3thrGcaT3x/bfgP+dIX94Fbsc5bbZFKW09CX/3apu4wtgbcmPZxC6xKBIzBYeVYYYNFx3xa6LZVkTyDLxJpV+DdlAaoTVDHifBViLS/BHrdFREPizHFbL6j+yJWQDLjagivrg9dGVIZWDBegg6AFJ+sd0GKKmYEtiKJkJHS8i4FY+9xBiPpohMMuEldOVlbSCjnlhsG9BeL9iVol2HnVySXNeoukFWQTH+V1udldkx85VFfledvpHiAe1y2udtAvV/zxXUo9EqKIwjMnfugY6nAHNJWkyG/LL+/C42vdPQM+p1o8AuRUHV5P/5Znwh+S8+6jvPybP2lVWjdEmsHkE9KPfFRyWFZ2oPFNPGfzrSYw+UhYDOZHNgK0glwmQ70ZpNsM+CR1rdqYrCpcKfg25wOmSI4js5/C6zlLjqDPAioyA5J73SGveP4U4KQSqqwT41lQ+PeJjMhFqtLnIGv1isqfFmYwQOAMIX2Owzn0=
        aws-region: us-east-1
    
    - name: Run CodeBuild
      run: |
        aws codebuild start-build --project-name GithubATnTPOC
    
    - name: Wait for CodeBuild completion
      run: |
        build_id=$(aws codebuild list-builds-for-project --project-name GithubATnTPOC --sort-order DESCENDING --max-items 1 --query 'ids[0]' --output text)
        aws codebuild wait build-completion --id $build_id
        build_status=$(aws codebuild batch-get-builds --ids $build_id --query 'builds[0].buildStatus' --output text)
        if [ "$build_status" != "SUCCEEDED" ]; then
          echo "CodeBuild failed with  status: $build_status"
          exit 1
        fi
