name: CodeBuild Runner Setup

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  trigger-codebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::813274479812:role/GithubATnTRole
        aws-region: us-east-1
    
    - name: Start CodeBuild
      id: start-build
      run: |
        # Start the build and capture the build ID
        BUILD_ID=$(aws codebuild start-build \
          --project-name GithubATnTPOC \
          --query 'build.id' \
          --output text)
        echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
        echo "Started build with ID: $BUILD_ID"
    
    - name: Wait for Build Completion
      run: |
        BUILD_ID="${{ steps.start-build.outputs.build_id }}"
        echo "Waiting for build $BUILD_ID to complete..."
        
        # Wait for build to complete and check status
        aws codebuild wait build-completion --ids "$BUILD_ID"
        
        # Get the final build status
        STATUS=$(aws codebuild batch-get-builds \
          --ids "$BUILD_ID" \
          --query 'builds[0].buildStatus' \
          --output text)
        
        echo "Build completed with status: $STATUS"
        
        if [ "$STATUS" != "SUCCEEDED" ]; then
          echo "Getting build logs..."
          aws codebuild batch-get-builds \
            --ids "$BUILD_ID" \
            --query 'builds[0].logs.deepLink' \
            --output text
          echo "Build failed with status: $STATUS"
          exit 1
        fi

    - name: Build Summary
      if: always()
      run: |
        BUILD_ID="${{ steps.start-build.outputs.build_id }}"
        echo "Build ID: $BUILD_ID"
        aws codebuild batch-get-builds \
          --ids "$BUILD_ID" \
          --query 'builds[0].[buildStatus,logs.deepLink]' \
          --output text
