name: CodeBuild Runner Setup

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  trigger-codebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIA32WXPXTCB7RFMSRH
        aws-secret-access-key: MH7Lff6mOS4HhIsZDl15jfKmnSZ23cIk8vYDm97n
        aws-session-token: IQoJb3JpZ2luX2VjENX//////////wEaCXVzLWVhc3QtMSJHMEUCIQCkovDIaEs5kBrKaujA7uONYeqapcOOOJYtzlpr4LozJQIgCbffCkaAkNaV+Lye7+kvxu+A2I6YM5FGqtmpI/w0d0gqqAIIjf//////////ARACGgw4MTMyNzQ0Nzk4MTIiDMmV6jyUP1NgtwkECyr8ARW25YmbyGyOOHgrwiZOcaDl7K+bzd9NAfItCLy+axRh/aZlG3D2rme678GkHsy/oTlNvp53BhrS4pWPtloAApWJUjfC6FttvYeISJdGxItqPo+PjvxK1qUehSTL8Ghsdz0GVg0fP/cmBqVz+FW4e8doQa4tKdLGthFF3KHY0X+Xq6IfLVm67/PZppiJMWv3OjFdVCvNtHgfHhTkYG/7TPvb9vc/E0/NindBPlsnU3HqvdIObZEUgjXMN94R5XZ5V5Am3xQkfD4xYSBw1HygDTb7fuknmAZC5V82m2b9GLkh4eeyLib0zKtkzVTKwEMmQEv0H0hSKuu8nVDAcjDd4eC6BjqdAZWiLSPEaCxrM82Jn74alDakg8TR/ChZJCDsQiineL0yLsqsoUhZzxYHj8qDZ9sl7jk8uOl0CH+1/nwNYNwj8ksGv/dJa2iT5NuQomEOFQxx1eyjTCJDCaUz8jb8heddn1s4+iolOmTH7+xAE/CzJksUPYbQ4i3oXod1gVMWNPAveEWTa+L/nlZs9yuNI4Z4QqQTPS9SnVHT/EVub3k=
        aws-region: us-east-1
    
    - name: Start CodeBuild
      id: start-build
      run: |
        # Start the build and capture the build ID
        BUILD_ID=$(aws codebuild start-build \
          --project-name GithubATnTPOC \
          --query 'build.id' \
          --output text)
        echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
        echo "Started build with ID: $BUILD_ID"
    
    - name: Wait for Build Completion
      run: |
        BUILD_ID="${{ steps.start-build.outputs.build_id }}"
        echo "Waiting for build $BUILD_ID to complete..."
        
        # Wait for build to complete and check status
        aws codebuild wait build-completion --ids "$BUILD_ID"
        
        # Get the final build status
        STATUS=$(aws codebuild batch-get-builds \
          --ids "$BUILD_ID" \
          --query 'builds[0].buildStatus' \
          --output text)
        
        echo "Build completed with status: $STATUS"
        
        if [ "$STATUS" != "SUCCEEDED" ]; then
          echo "Getting build logs..."
          aws codebuild batch-get-builds \
            --ids "$BUILD_ID" \
            --query 'builds[0].logs.deepLink' \
            --output text
          echo "Build failed with status: $STATUS"
          exit 1
        fi

    - name: Build Summary
      if: always()
      run: |
        BUILD_ID="${{ steps.start-build.outputs.build_id }}"
        echo "Build ID: $BUILD_ID"
        aws codebuild batch-get-builds \
          --ids "$BUILD_ID" \
          --query 'builds[0].[buildStatus,logs.deepLink]' \
          --output text
