name: Test Runner

on:
  workflow_dispatch:
    inputs:
      runner_name:
        description: 'Name of the runner to test'
        required: true
        default: 'aws-codebuild-runner'

jobs:
  test:
    runs-on: ${{ github.event.inputs.runner_name }}
    steps:
      - name: Check runner
        run: |
          echo "Hello from ${{ runner.name }}!"
          echo "OS: $(uname -a)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Environment variables:"
          env
