name: Test CodeBuild Runner

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, aws-codebuild]
    steps:
      - name: Simple Test
        run: |
          echo "Hello from CodeBuild runner!"
          pwd
          ls -la
          whoami
          echo "Runner name: ${{ runner.name }}"
          echo "Runner labels: ${{ runner.labels }}"
