name: Test CodeBuild Runner

on:
  workflow_dispatch:  
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, aws-codebuild]  # Exactly matching the runner labels
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Test Environment
        run: |
          echo "Hello from CodeBuild runner!"
          echo "Current directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          
      - name: Test AWS Authentication
        run: |
          aws sts get-caller-identity
          
      - name: Test Basic Commands
        run: |
          echo "Testing system commands..."
          uname -a
          python3 --version
          node --version
