name: Test Runner Flow
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Test
        run: |
          echo "Testing runner flow"
          echo "Runner name: ${{ runner.name }}"
          date
